namespace Luban.Unreal;

public static class ConstStrings
{
    public const string IncludePerfix = "Table/Luban";
    public const string APIName = "WANG_API";
    public const string APINameOption = "unrealPluginAPIName";
    public const string DataTableNameField = "Name";
    public const string PackageDirCfgName = "unrealPackageDir";
    public const string UnrealImportGroupName = "ImportGroups";
    public const string HeaderFileRoot = "Public";
    public const string CppFileRoot = "Private";
    public const string CppSufix = ".cpp";
    public const string HeaderSufix = ".h";
    public const string UnrealImportDestinationParamName = "unrealImportDestination";
    public const string HeaderSuffixDefault = "Exe";
    public const string HeaderSuffixParam = "unrealHeaderSuffix";
    public const string AUTO_GENERATE_UNREAL_C_LIKE = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     Generated from file {0}.
// </auto-generated>
//------------------------------------------------------------------------------
";

    public static string GetHeaderSuffix()
    {
       return EnvManager.Current.GetOptionOrDefault("", HeaderSuffixParam, true, HeaderSuffixDefault);
    }
}
